services:
  - type: web
    name: edugestion
    env: static
    buildCommand: npm run build
    publishPath: dist/edugestion
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CURRENCY
        sync: false
