/**
 * Pre-build script that reads .env and generates src/environments/environment.ts
 * Run this before `ng serve` or `ng build` to inject environment variables.
 * 
 * Usage: node set-env.js
 */
const fs = require('fs');
const path = require('path');

// Read .env file and merge with process environment so Render can inject values
const envPath = path.resolve(__dirname, '.env');
const envVars = {};

if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf-8');
    envContent.split('\n').forEach(line => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
            const [key, ...valueParts] = trimmed.split('=');
            envVars[key.trim()] = valueParts.join('=').trim();
        }
    });
}

function readExistingEnvironmentValues() {
    const existingEnvPath = path.resolve(__dirname, 'src/environments/environment.ts');
    if (!fs.existsSync(existingEnvPath)) {
        return {};
    }

    const content = fs.readFileSync(existingEnvPath, 'utf-8');
    const getMatch = (key) => {
        const match = content.match(new RegExp(`${key}:\\s*['\"]([^'\"]*)['\"]`));
        return match ? match[1] : '';
    };

    return {
        SUPABASE_URL: getMatch('supabaseUrl'),
        SUPABASE_ANON_KEY: getMatch('supabaseAnonKey'),
        GEMINI_API_KEY: getMatch('geminiApiKey'),
        PAYPAL_CLIENT_ID: getMatch('paypalClientId'),
        PAYPAL_CURRENCY: getMatch('paypalCurrency') || 'MXN'
    };
}

const existingEnvVars = readExistingEnvironmentValues();

const resolvedEnv = {
    SUPABASE_URL: process.env.SUPABASE_URL || envVars.SUPABASE_URL || existingEnvVars.SUPABASE_URL || '',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || envVars.SUPABASE_ANON_KEY || existingEnvVars.SUPABASE_ANON_KEY || '',
    GEMINI_API_KEY: process.env.GEMINI_API_KEY || envVars.GEMINI_API_KEY || existingEnvVars.GEMINI_API_KEY || '',
    PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID || envVars.PAYPAL_CLIENT_ID || existingEnvVars.PAYPAL_CLIENT_ID || '',
    PAYPAL_CURRENCY: process.env.PAYPAL_CURRENCY || envVars.PAYPAL_CURRENCY || existingEnvVars.PAYPAL_CURRENCY || 'MXN'
};

// Generate environment.ts
const environmentContent = `// ⚠️ AUTO-GENERATED by set-env.js — Do not edit manually.
// Edit .env instead and run: node set-env.js
export const environment = {
  production: false,
    supabaseUrl: '${resolvedEnv.SUPABASE_URL}',
    supabaseAnonKey: '${resolvedEnv.SUPABASE_ANON_KEY}',
    geminiApiKey: '${resolvedEnv.GEMINI_API_KEY}',
    paypalClientId: '${resolvedEnv.PAYPAL_CLIENT_ID}',
    paypalCurrency: '${resolvedEnv.PAYPAL_CURRENCY}'
};
`;

const outputPath = path.resolve(__dirname, 'src/environments/environment.ts');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, environmentContent, 'utf-8');

console.log('✅ environment.ts generated from .env');
