/**
 * Pre-build script that reads .env and generates src/environments/environment.ts
 * Run this before `ng serve` or `ng build` to inject environment variables.
 * 
 * Usage: node set-env.js
 */
const fs = require('fs');
const path = require('path');

// Read .env file
const envPath = path.resolve(__dirname, '.env');
const envVars = {};

if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf-8');
    envContent.split('\n').forEach(line => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
            const [key, ...valueParts] = trimmed.split('=');
            envVars[key.trim()] = valueParts.join('=').trim();
        }
    });
}

// Generate environment.ts
const environmentContent = `// ⚠️ AUTO-GENERATED by set-env.js — Do not edit manually.
// Edit .env instead and run: node set-env.js
export const environment = {
  production: false,
  supabaseUrl: '${envVars.SUPABASE_URL || ''}',
  supabaseAnonKey: '${envVars.SUPABASE_ANON_KEY || ''}',
  geminiApiKey: '${envVars.GEMINI_API_KEY || ''}',
  paypalClientId: '${envVars.PAYPAL_CLIENT_ID || ''}',
  paypalCurrency: '${envVars.PAYPAL_CURRENCY || 'MXN'}'
};
`;

const outputPath = path.resolve(__dirname, 'src/environments/environment.ts');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, environmentContent, 'utf-8');

console.log('✅ environment.ts generated from .env');
