// ⚠️ AUTO-GENERATED by set-env.js — Do not edit manually.
// Edit .env instead and run: node set-env.js
export const environment = {
  production: false,
    supabaseUrl: 'https://ngqcsposkknbmzgnalba.supabase.co',
    supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ncWNzcG9za2tuYm16Z25hbGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMTI4MTYsImV4cCI6MjA4NDU4ODgxNn0.14VFmURKH0VBoi5--7UFWQj5wmHkXoveXdIVkkQEQFE',
    geminiApiKey: 'AIzaSyDGN_RV4ZyIN8AworYVgem9dDB7tAlkIS0',
    paypalClientId: 'AUlAiVShMk-iOw4y7LiUcEf_s6wAtxNVgXYanSDfqo4clevqtuAxadowKxFZTrkEFQ3k2pYj1mUnpPaG',
    paypalCurrency: 'MXN'
};
